### ISSUE TITLE
Carthage support failing to build

### ISSUE THREAD

**Issue by hasanPrestoq** [Maru-zhang/SwiftyEventBus#22]
the dependencies on 
Nimble
Quick
RxSwift

Are exposed in the Podfile, but no Cartfile exists to express the dependencies
Please add a Cartfile so that I can use without having to manually compile.

**Comment by hasanPrestoq** [comment]
error: /Users/hasan/Documents/DemoDev/SwiftyEventBus/Carthage/Checkouts/SwiftyEventBus/Pods/Target Support Files/Pods-SwiftyEventBus/Pods-SwiftyEventBus.release.xcconfig: unable to open file (in target "SwiftyEventBus" in project "SwiftyEventBus") (in target 'SwiftyEventBus')

Build system information
error: /Users/hasan/Documents/DemoDev/SwiftyEventBus/Carthage/Checkouts/SwiftyEventBus/Pods/Target Support Files/Pods-SwiftyEventBus/Pods-SwiftyEventBus.release.xcconfig: unable to open file (in target "SwiftyEventBus" in project "SwiftyEventBus") (in target 'SwiftyEventBus')

Build system information
error: /Users/hasan/Documents/DemoDev/SwiftyEventBus/Carthage/Checkouts/SwiftyEventBus/Pods/Target Support Files/Pods-SwiftyEventBus/Pods-SwiftyEventBus.release.xcconfig: unable to open file (in target "SwiftyEventBus" in project "SwiftyEventBus") (in target 'SwiftyEventBus')

** ARCHIVE FAILED **

This indicates the expectation of a directory named Pods, which is not in the checked out version of the code. This causes the "Carthage update" command to fail.

**Comment by Maru-zhang** [comment]
It fixed now in develop branch, thank you.
