### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Coder-Star** [Maru-zhang/SwiftyEventBus#28]
```
public func register<T>(on mode: DispatchMode = .same, priority: EventBusPriority = .`default`, messageEvent: @escaping (T) -> Void) -> EventSubscription<T> {
        return middleWare.register(on: mode, priority: priority, messageEvent: messageEvent)
    }
```
是将NSNotificationName以及传递的数据都交给了messageEvent了吗？ 是通过messageEvent来判断来自不同的事件吗？

**Comment by Maru-zhang** [comment]
主要是根据`T`这个泛型的类型来判断来自不同的事件，相当于这里用的是一个隐式的`NSNotificationName `，而这个`NSNotificationName`就是这个`T`类型的`NameSpace` + `类型名称字符串`。

**Comment by Coder-Star** [comment]
> 主要是根据`T`这个泛型的类型来判断来自不同的事件，相当于这里用的是一个隐式的`NSNotificationName `，而这个`NSNotificationName`就是这个`T`类型的`NameSpace` + `类型名称字符串`。

如果两个事件对应的这个泛型类型一样怎么处理，比如说我将所有事件的标识都交给一个enum去管理

**Comment by Maru-zhang** [comment]
没有实际的例子，但我理解你的这种case应该也可以用单独的`EventBus`实例来进行隔离，用两个不同的`EventBust`然后进行分别的订阅，这样可以解决你的问题么？

**Comment by Coder-Star** [comment]
> 没有实际的例子，但我理解你的这种case应该也可以用单独的`EventBus`实例来进行隔离，用两个不同的`EventBust`然后进行分别的订阅，这样可以解决你的问题么？

如果使用两个不同EventBus实例来解决这个需求，可以解决这个问题，但是我觉得这种方式不是很好，如果enum中有很多个case 那就需要定义很多个EventBus实例去对应 这样消耗内存 还是建议能考虑在注册时以及发送时传入一个名字进入 而不是简单的使用闭包类型来当做判断不同事件的标识

**Comment by Maru-zhang** [comment]
可以举个具体的场景或者例子吗？在我的理解一般`enum`的情况下所有的case应该都是要关心的，应该不是有多个case对应多个`EventBus`，而是有多个业务场景对应多个`EventBus`，这样的话应该是合理的。

**Comment by Coder-Star** [comment]
> 可以举个具体的场景或者例子吗？在我的理解一般`enum`的情况下所有的case应该都是要关心的，应该不是有多个case对应多个`EventBus`，而是有多个业务场景对应多个`EventBus`，这样的话应该是合理的。

你qq是多少 直接qq沟通一下吧

**Comment by Maru-zhang** [comment]
加你了
